import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='bg-red-300 shadow-lg'>
          <div className='max-w-6xl mx-3 px-4'>
            <div className='flex justify-between'>
              <div className='flex space-x-7'>
                <div>
                  <span className='font-bold text-white text-lg'>Selamat Datang Di Website</span>
                </div>
              </div>
            </div>
          </div>
        </nav>
        
        
        
        
        {children}</body>
    </html>
  )
}
